### ISSUE TITLE
Students Intermittently Not Receiving Emails for pt-web-compass2

### ISSUE THREAD

**Issue by kbluescode** [lighthouse-labs/laser_shark#189]
Had a student message me over 2 class lecture emails that didn't get sent to them. One or two ended up in spam, but some just didn't get to them at all. On my end, upon saving the lecture notes, it still popped up with the flash message that students were notified. Only one student has come to me with this issue so far, but they apparently didn't receive 2 of the 12 emails.

**Comment by Sailias** [comment]
@kbluescode What are they using as their mail provider?  gmail or something custom?
