### ISSUE TITLE
Testing Integration

### ISSUE THREAD

**Issue by krsnachandra** [lighthouse-labs/laser_shark#198]
Is anyone annoyed by my testing? Sorry! I'm trying to figure out an integration. GitHub will let you mute this thread though!

**Comment by jmatsuba** [comment]
Not really, but a question.
Does it have to be this specific repo, why not a new repo with nobody else on it?

**Comment by krsnachandra** [comment]
Great question @jmatsuba!
At first it seemed that I was restricted to use a repo from one of the organizations I am a part of. I have now found a way to test with a personal repo so I'm not testing on here anymore. Sorry if my testing was annoying :)
I had figured that since this repo is old it would be irrelevant. Now I know that I should check for who is watching a repo! Sorry again!
