### ISSUE TITLE
Reform the Reform gem?

### ISSUE THREAD

**Issue by monicao** [lighthouse-labs/laser_shark#28]
I'm concerned that this gem causes code duplication and introduces the potential for errors. 

We already had a small bug. The user model did not validate that the first_name, last_name, email and phone_number fields are present. The form was validating it, but we need validations on the model too (if the app updates the user model internally, we still need to maintain data integrity.).

With Reform we have to make sure that our form validations match our model validations. This is code duplication, and imo it seems like overkill. I want to propose that we take out the Reform gem.

See PR for how the registration form looks like without reform: https://github.com/lighthouse-labs/laser_shark/pull/27

What does everybody think?

**Comment by davidvandusen** [comment]
I'm doing some clean up, so I'm closing this issue.
