### ISSUE TITLE
Bug: Activity/schedule view permissions expire for alumni after Week 14

### ISSUE THREAD

**Issue by kriscooke** [lighthouse-labs/laser_shark#79]
At the end of Week 14 (for graduates), clicking on any schedule day other than W1D1 gives the following flash message: "Access not allowed yet!" (see screenshot). Access is meant to continue, so perhaps something is causing the activity permissions to expire.

![compass_bug](https://cloud.githubusercontent.com/assets/5522075/4966083/b63cb4ce-67aa-11e4-96d2-2164fff3f228.png)

**Comment by davidvandusen** [comment]
This issue was resolved at some point, I believe. Please let me know if I'm wrong. Closing the issue.
